# Generated by Django 4.2.3 on 2023-08-10 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="activate",
            new_name="active",
        ),
    ]
